### ISSUE TITLE
Customer API Support

### ISSUE THREAD

**Issue by adgsenpai** [calvinmuller/takealot-api#1]
do you think you could make an API customers to interact with. I would like to do my own personal app to measure how much I'm spending at Takealot?

**Comment by calvinmuller** [comment]
hey man, i'll take a look at their API. Should be achievable given their is no signature of some sort. Will revert soonest.

**Comment by calvinmuller** [comment]
Added support in  commit 714f47cf716e0e1d21bd243bfc41f4e2ff9d0066

check the tests on how to use.
https://github.com/calvinmuller/takealot-api/blob/master/tests/TakealotTests.php

**Comment by adgsenpai** [comment]
Thank you! @calvinmuller

**Comment by adgsenpai** [comment]
@calvinmuller Where could one find Takealot's Developer Docs. Would like to make a module package for Python.

**Comment by calvinmuller** [comment]
@adgsenpai Python is not really my thing, you could just take this code and port it. Should be pretty straight forward.

I dont think they have developer docs, I use the app and reverse engineer the API calls from there using a proxy eg. Charles Proxy.

**Comment by adgsenpai** [comment]
> Charles Proxy

That's cool thanks again :-)
